GET http://localhost:5000/pruebas/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "María",
    "lastName": "La del Barrio",
    "email": "thalia@gmail.com",
    "role": "user"
}